name: docs_pages_workflow
 
# execute this workflow automatically when we push to master
on:
  push:
    branches:
      - main
      - workflow-dev
 
jobs:
 
  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9
 
      - name: Install dependencies
        run: |
          python -m pip install -U sphinx
          python -m pip install sphinx-rtd-theme
          python -m pip install sphinx-autoapi
          python -m pip install myst-parser==1.0.0
      
      - name: Make the sphinx docs
        run: |
          make -C docs clean 
          sphinx-build -M html docs/docsource docs/docbuild
      
      #sphinx-apidoc -e -M -d 8 -o ./api ../../nova-server/nova_server      
      # cd docs/docsource
      #- name: Init new repo in dist folder and commit generated files
      #  run: |
      #    cd docs/docbuild/
      #    git init
      #    touch .nojekyll
      #    git add -A
      #    git config --local user.email "action@github.com"
      #    git config --local user.name "GitHub Action"
      #    git commit -m 'deploy'

      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: docs
          force: true
          #directory: ./docs/docbuild
